site_name: Lottie Animation Docs
nav:
- Home: index.md
- Specs:
  - specs/animation.md
  - Properties:
    - specs/properties/prop-types.md
    - specs/properties/animatable-properties.md
  - specs/chars.md
  - specs/assets.md
  - Layers:
    - specs/layers/common.md
    - specs/layers/solid.md
    - specs/layers/shapes.md
    - specs/layers/text.md
    - specs/layers/image.md
    - specs/layers/null.md
    - specs/layers/precomp.md
- Profiles:
  - profiles/index.md
  - Layers: profiles/layers/index.md
markdown_extensions:
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 
  - markdown_include.include:
      base_path: docs
plugins:
  - tooltips
extra_css:
  - css/hint.min.css
theme:
  name: material
  palette:
    primary: '#00ff00'
    accent: '#00ff00'